services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

  api:
    build:
      context: ./api
    environment:
      - TP_AUTH_COOKIE=${TP_AUTH_COOKIE}
      - TP_ATHLETE_ID=6257536
    expose:
      - "8000"
    restart: unless-stopped
